INSERT INTO country_code(code3, code2, country) VALUES('GHA', 'GH', '가나');
INSERT INTO country_code(code3, code2, country) VALUES('GAB', 'GA', '가봉');
INSERT INTO country_code(code3, code2, country) VALUES('GUY', 'GY', '가이아나');
INSERT INTO country_code(code3, code2, country) VALUES('GMB', 'GM', '감비아');
INSERT INTO country_code(code3, code2, country) VALUES('GGY', 'GG', '건지섬');
INSERT INTO country_code(code3, code2, country) VALUES('GLP', 'GP', '과들루프');
INSERT INTO country_code(code3, code2, country) VALUES('GTM', 'GT', '과테말라');
INSERT INTO country_code(code3, code2, country) VALUES('GUM', 'GU', '괌');
INSERT INTO country_code(code3, code2, country) VALUES('GRD', 'GD', '그레나다');
INSERT INTO country_code(code3, code2, country) VALUES('GRC', 'GR', '그리스');
INSERT INTO country_code(code3, code2, country) VALUES('GRL', 'GL', '그린란드');
INSERT INTO country_code(code3, code2, country) VALUES('GIN', 'GN', '기니');
INSERT INTO country_code(code3, code2, country) VALUES('GNB', 'GW', '기니비사우');
INSERT INTO country_code(code3, code2, country) VALUES('NAM', 'NA', '나미비아');
INSERT INTO country_code(code3, code2, country) VALUES('NRU', 'NR', '나우루');
INSERT INTO country_code(code3, code2, country) VALUES('NGA', 'NG', '나이지리아');
INSERT INTO country_code(code3, code2, country) VALUES('ATA', 'AQ', '남극');
INSERT INTO country_code(code3, code2, country) VALUES('SSD', 'SS', '남수단');
INSERT INTO country_code(code3, code2, country) VALUES('ZAF', 'ZA', '남아프리카 공화국');
INSERT INTO country_code(code3, code2, country) VALUES('NLD', 'NL', '네덜란드');
INSERT INTO country_code(code3, code2, country) VALUES('NPL', 'NP', '네팔');
INSERT INTO country_code(code3, code2, country) VALUES('NOR', 'NO', '노르웨이');
INSERT INTO country_code(code3, code2, country) VALUES('NFK', 'NF', '노퍽섬');
INSERT INTO country_code(code3, code2, country) VALUES('NCL', 'NC', '누벨칼레도니');
INSERT INTO country_code(code3, code2, country) VALUES('NZL', 'NZ', '뉴질랜드');
INSERT INTO country_code(code3, code2, country) VALUES('NIU', 'NU', '니우에');
INSERT INTO country_code(code3, code2, country) VALUES('NER', 'NE', '니제르');
INSERT INTO country_code(code3, code2, country) VALUES('NIC', 'NI', '니카라과');
INSERT INTO country_code(code3, code2, country) VALUES('KOR', 'KR', '대한민국');
INSERT INTO country_code(code3, code2, country) VALUES('DNK', 'DK', '덴마크');
INSERT INTO country_code(code3, code2, country) VALUES('DOM', 'DO', '도미니카 공화국');
INSERT INTO country_code(code3, code2, country) VALUES('DMA', 'DM', '도미니카 연방');
INSERT INTO country_code(code3, code2, country) VALUES('TLS', 'TL', '동티모르');
INSERT INTO country_code(code3, code2, country) VALUES('DEU', 'DE', '독일');
INSERT INTO country_code(code3, code2, country) VALUES('LAO', 'LA', '라오스');
INSERT INTO country_code(code3, code2, country) VALUES('LBR', 'LR', '라이베리아');
INSERT INTO country_code(code3, code2, country) VALUES('LVA', 'LV', '라트비아');
INSERT INTO country_code(code3, code2, country) VALUES('RUS', 'RU', '러시아');
INSERT INTO country_code(code3, code2, country) VALUES('LBN', 'LB', '레바논');
INSERT INTO country_code(code3, code2, country) VALUES('LSO', 'LS', '레소토');
INSERT INTO country_code(code3, code2, country) VALUES('REU', 'RE', '레위니옹');
INSERT INTO country_code(code3, code2, country) VALUES('ROU', 'RO', '루마니아');
INSERT INTO country_code(code3, code2, country) VALUES('LUX', 'LU', '룩셈부르크');
INSERT INTO country_code(code3, code2, country) VALUES('RWA', 'RW', '르완다');
INSERT INTO country_code(code3, code2, country) VALUES('LBY', 'LY', '리비아');
INSERT INTO country_code(code3, code2, country) VALUES('LTU', 'LT', '리투아니아');
INSERT INTO country_code(code3, code2, country) VALUES('LIE', 'LI', '리히텐슈타인');
INSERT INTO country_code(code3, code2, country) VALUES('MDG', 'MG', '마다가스카르');
INSERT INTO country_code(code3, code2, country) VALUES('MTQ', 'MQ', '마르티니크');
INSERT INTO country_code(code3, code2, country) VALUES('MHL', 'MH', '마셜 제도');
INSERT INTO country_code(code3, code2, country) VALUES('MYT', 'YT', '마요트');
INSERT INTO country_code(code3, code2, country) VALUES('MAC', 'MO', '마카오');
INSERT INTO country_code(code3, code2, country) VALUES('MWI', 'MW', '말라위');
INSERT INTO country_code(code3, code2, country) VALUES('MYS', 'MY', '말레이시아');
INSERT INTO country_code(code3, code2, country) VALUES('MLI', 'ML', '말리');
INSERT INTO country_code(code3, code2, country) VALUES('IMN', 'IM', '맨섬');
INSERT INTO country_code(code3, code2, country) VALUES('MEX', 'MX', '멕시코');
INSERT INTO country_code(code3, code2, country) VALUES('MCO', 'MC', '모나코');
INSERT INTO country_code(code3, code2, country) VALUES('MAR', 'MA', '모로코');
INSERT INTO country_code(code3, code2, country) VALUES('MUS', 'MU', '모리셔스');
INSERT INTO country_code(code3, code2, country) VALUES('MRT', 'MR', '모리타니');
INSERT INTO country_code(code3, code2, country) VALUES('MOZ', 'MZ', '모잠비크');
INSERT INTO country_code(code3, code2, country) VALUES('MNE', 'ME', '몬테네그로');
INSERT INTO country_code(code3, code2, country) VALUES('MSR', 'MS', '몬트세랫');
INSERT INTO country_code(code3, code2, country) VALUES('MDA', 'MD', '몰도바');
INSERT INTO country_code(code3, code2, country) VALUES('MDV', 'MV', '몰디브');
INSERT INTO country_code(code3, code2, country) VALUES('MLT', 'MT', '몰타');
INSERT INTO country_code(code3, code2, country) VALUES('MNG', 'MN', '몽골');
INSERT INTO country_code(code3, code2, country) VALUES('USA', 'US', '미국');
INSERT INTO country_code(code3, code2, country) VALUES('UMI', 'UM', '미국령 군소 제도');
INSERT INTO country_code(code3, code2, country) VALUES('VIR', 'VI', '미국령 버진아일랜드');
INSERT INTO country_code(code3, code2, country) VALUES('MMR', 'MM', '미얀마');
INSERT INTO country_code(code3, code2, country) VALUES('FSM', 'FM', '미크로네시아 연방');
INSERT INTO country_code(code3, code2, country) VALUES('VUT', 'VU', '바누아투');
INSERT INTO country_code(code3, code2, country) VALUES('BHR', 'BH', '바레인');
INSERT INTO country_code(code3, code2, country) VALUES('BRB', 'BB', '바베이도스');
INSERT INTO country_code(code3, code2, country) VALUES('VAT', 'VA', '바티칸 시국');
INSERT INTO country_code(code3, code2, country) VALUES('BHS', 'BS', '바하마');
INSERT INTO country_code(code3, code2, country) VALUES('BGD', 'BD', '방글라데시');
INSERT INTO country_code(code3, code2, country) VALUES('BMU', 'BM', '버뮤다');
INSERT INTO country_code(code3, code2, country) VALUES('BEN', 'BJ', '베냉');
INSERT INTO country_code(code3, code2, country) VALUES('VEN', 'VE', '베네수엘라');
INSERT INTO country_code(code3, code2, country) VALUES('VNM', 'VN', '베트남');
INSERT INTO country_code(code3, code2, country) VALUES('BEL', 'BE', '벨기에');
INSERT INTO country_code(code3, code2, country) VALUES('BLR', 'BY', '벨라루스');
INSERT INTO country_code(code3, code2, country) VALUES('BLZ', 'BZ', '벨리즈');
INSERT INTO country_code(code3, code2, country) VALUES('BES', 'BQ', '보네르섬');
INSERT INTO country_code(code3, code2, country) VALUES('BIH', 'BA', '보스니아 헤르체고비나');
INSERT INTO country_code(code3, code2, country) VALUES('BWA', 'BW', '보츠와나');
INSERT INTO country_code(code3, code2, country) VALUES('BOL', 'BO', '볼리비아');
INSERT INTO country_code(code3, code2, country) VALUES('BDI', 'BI', '부룬디');
INSERT INTO country_code(code3, code2, country) VALUES('BFA', 'BF', '부르키나파소');
INSERT INTO country_code(code3, code2, country) VALUES('BVT', 'BV', '부베섬');
INSERT INTO country_code(code3, code2, country) VALUES('BTN', 'BT', '부탄');
INSERT INTO country_code(code3, code2, country) VALUES('MNP', 'MP', '북마리아나 제도');
INSERT INTO country_code(code3, code2, country) VALUES('MKD', 'MK', '북마케도니아');
INSERT INTO country_code(code3, code2, country) VALUES('BGR', 'BG', '불가리아');
INSERT INTO country_code(code3, code2, country) VALUES('BRA', 'BR', '브라질');
INSERT INTO country_code(code3, code2, country) VALUES('BRN', 'BN', '브루나이');
INSERT INTO country_code(code3, code2, country) VALUES('WSM', 'WS', '사모아');
INSERT INTO country_code(code3, code2, country) VALUES('SAU', 'SA', '사우디아라비아');
INSERT INTO country_code(code3, code2, country) VALUES('SGS', 'GS', '사우스조지아 사우스샌드위치 제도');
INSERT INTO country_code(code3, code2, country) VALUES('SMR', 'SM', '산마리노');
INSERT INTO country_code(code3, code2, country) VALUES('STP', 'ST', '상투메 프린시페');
INSERT INTO country_code(code3, code2, country) VALUES('MAF', 'MF', '생마르탱');
INSERT INTO country_code(code3, code2, country) VALUES('BLM', 'BL', '생바르텔레미');
INSERT INTO country_code(code3, code2, country) VALUES('SPM', 'PM', '생피에르 미클롱');
INSERT INTO country_code(code3, code2, country) VALUES('ESH', 'EH', '서사하라');
INSERT INTO country_code(code3, code2, country) VALUES('SEN', 'SN', '세네갈');
INSERT INTO country_code(code3, code2, country) VALUES('SRB', 'RS', '세르비아');
INSERT INTO country_code(code3, code2, country) VALUES('SYC', 'SC', '세이셸');
INSERT INTO country_code(code3, code2, country) VALUES('LCA', 'LC', '세인트루시아');
INSERT INTO country_code(code3, code2, country) VALUES('VCT', 'VC', '세인트빈센트 그레나딘');
INSERT INTO country_code(code3, code2, country) VALUES('KNA', 'KN', '세인트키츠 네비스');
INSERT INTO country_code(code3, code2, country) VALUES('SHN', 'SH', '세인트헬레나');
INSERT INTO country_code(code3, code2, country) VALUES('SOM', 'SO', '소말리아');
INSERT INTO country_code(code3, code2, country) VALUES('SLB', 'SB', '솔로몬 제도');
INSERT INTO country_code(code3, code2, country) VALUES('SDN', 'SD', '수단');
INSERT INTO country_code(code3, code2, country) VALUES('SUR', 'SR', '수리남');
INSERT INTO country_code(code3, code2, country) VALUES('LKA', 'LK', '스리랑카');
INSERT INTO country_code(code3, code2, country) VALUES('SJM', 'SJ', '스발바르 얀마옌');
INSERT INTO country_code(code3, code2, country) VALUES('SWE', 'SE', '스웨덴');
INSERT INTO country_code(code3, code2, country) VALUES('CHE', 'CH', '스위스');
INSERT INTO country_code(code3, code2, country) VALUES('ESP', 'ES', '스페인');
INSERT INTO country_code(code3, code2, country) VALUES('SVK', 'SK', '슬로바키아');
INSERT INTO country_code(code3, code2, country) VALUES('SVN', 'SI', '슬로베니아');
INSERT INTO country_code(code3, code2, country) VALUES('SYR', 'SY', '시리아');
INSERT INTO country_code(code3, code2, country) VALUES('SLE', 'SL', '시에라리온');
INSERT INTO country_code(code3, code2, country) VALUES('SXM', 'SX', '신트마르턴');
INSERT INTO country_code(code3, code2, country) VALUES('SGP', 'SG', '싱가포르');
INSERT INTO country_code(code3, code2, country) VALUES('ARE', 'AE', '아랍에미리트');
INSERT INTO country_code(code3, code2, country) VALUES('ABW', 'AW', '아루바');
INSERT INTO country_code(code3, code2, country) VALUES('ARM', 'AM', '아르메니아');
INSERT INTO country_code(code3, code2, country) VALUES('ARG', 'AR', '아르헨티나');
INSERT INTO country_code(code3, code2, country) VALUES('ASM', 'AS', '아메리칸사모아');
INSERT INTO country_code(code3, code2, country) VALUES('ISL', 'IS', '아이슬란드');
INSERT INTO country_code(code3, code2, country) VALUES('HTI', 'HT', '아이티');
INSERT INTO country_code(code3, code2, country) VALUES('IRL', 'IE', '아일랜드');
INSERT INTO country_code(code3, code2, country) VALUES('AZE', 'AZ', '아제르바이잔');
INSERT INTO country_code(code3, code2, country) VALUES('AFG', 'AF', '아프가니스탄');
INSERT INTO country_code(code3, code2, country) VALUES('AND', 'AD', '안도라');
INSERT INTO country_code(code3, code2, country) VALUES('ALB', 'AL', '알바니아');
INSERT INTO country_code(code3, code2, country) VALUES('DZA', 'DZ', '알제리');
INSERT INTO country_code(code3, code2, country) VALUES('AGO', 'AO', '앙골라');
INSERT INTO country_code(code3, code2, country) VALUES('ATG', 'AG', '앤티가 바부다');
INSERT INTO country_code(code3, code2, country) VALUES('AIA', 'AI', '앵귈라');
INSERT INTO country_code(code3, code2, country) VALUES('ERI', 'ER', '에리트레아');
INSERT INTO country_code(code3, code2, country) VALUES('SWZ', 'SZ', '에스와티니');
INSERT INTO country_code(code3, code2, country) VALUES('EST', 'EE', '에스토니아');
INSERT INTO country_code(code3, code2, country) VALUES('ECU', 'EC', '에콰도르');
INSERT INTO country_code(code3, code2, country) VALUES('ETH', 'ET', '에티오피아');
INSERT INTO country_code(code3, code2, country) VALUES('SLV', 'SV', '엘살바도르');
INSERT INTO country_code(code3, code2, country) VALUES('GBR', 'GB', '영국');
INSERT INTO country_code(code3, code2, country) VALUES('VGB', 'VG', '영국령 버진아일랜드');
INSERT INTO country_code(code3, code2, country) VALUES('IOT', 'IO', '영국령 인도양 지역');
INSERT INTO country_code(code3, code2, country) VALUES('YEM', 'YE', '예멘');
INSERT INTO country_code(code3, code2, country) VALUES('OMN', 'OM', '오만');
INSERT INTO country_code(code3, code2, country) VALUES('AUS', 'AU', '오스트레일리아');
INSERT INTO country_code(code3, code2, country) VALUES('AUT', 'AT', '오스트리아');
INSERT INTO country_code(code3, code2, country) VALUES('HND', 'HN', '온두라스');
INSERT INTO country_code(code3, code2, country) VALUES('ALA', 'AX', '올란드 제도');
INSERT INTO country_code(code3, code2, country) VALUES('WLF', 'WF', '왈리스 퓌튀나');
INSERT INTO country_code(code3, code2, country) VALUES('JOR', 'JO', '요르단');
INSERT INTO country_code(code3, code2, country) VALUES('UGA', 'UG', '우간다');
INSERT INTO country_code(code3, code2, country) VALUES('URY', 'UY', '우루과이');
INSERT INTO country_code(code3, code2, country) VALUES('UZB', 'UZ', '우즈베키스탄');
INSERT INTO country_code(code3, code2, country) VALUES('UKR', 'UA', '우크라이나');
INSERT INTO country_code(code3, code2, country) VALUES('IRQ', 'IQ', '이라크');
INSERT INTO country_code(code3, code2, country) VALUES('IRN', 'IR', '이란');
INSERT INTO country_code(code3, code2, country) VALUES('ISR', 'IL', '이스라엘');
INSERT INTO country_code(code3, code2, country) VALUES('EGY', 'EG', '이집트');
INSERT INTO country_code(code3, code2, country) VALUES('ITA', 'IT', '이탈리아');
INSERT INTO country_code(code3, code2, country) VALUES('IND', 'IN', '인도');
INSERT INTO country_code(code3, code2, country) VALUES('IDN', 'ID', '인도네시아');
INSERT INTO country_code(code3, code2, country) VALUES('JPN', 'JP', '일본');
INSERT INTO country_code(code3, code2, country) VALUES('JAM', 'JM', '자메이카');
INSERT INTO country_code(code3, code2, country) VALUES('ZMB', 'ZM', '잠비아');
INSERT INTO country_code(code3, code2, country) VALUES('JEY', 'JE', '저지섬');
INSERT INTO country_code(code3, code2, country) VALUES('GNQ', 'GQ', '적도 기니');
INSERT INTO country_code(code3, code2, country) VALUES('PRK', 'KP', '조선민주주의인민공화국');
INSERT INTO country_code(code3, code2, country) VALUES('GEO', 'GE', '조지아');
INSERT INTO country_code(code3, code2, country) VALUES('CHN', 'CN', '중국');
INSERT INTO country_code(code3, code2, country) VALUES('CAF', 'CF', '중앙아프리카 공화국');
INSERT INTO country_code(code3, code2, country) VALUES('TWN', 'TW', '중화민국');
INSERT INTO country_code(code3, code2, country) VALUES('DJI', 'DJ', '지부티');
INSERT INTO country_code(code3, code2, country) VALUES('GIB', 'GI', '지브롤터');
INSERT INTO country_code(code3, code2, country) VALUES('ZWE', 'ZW', '짐바브웨');
INSERT INTO country_code(code3, code2, country) VALUES('TCD', 'TD', '차드');
INSERT INTO country_code(code3, code2, country) VALUES('CZE', 'CZ', '체코');
INSERT INTO country_code(code3, code2, country) VALUES('CHL', 'CL', '칠레');
INSERT INTO country_code(code3, code2, country) VALUES('CMR', 'CM', '카메룬');
INSERT INTO country_code(code3, code2, country) VALUES('CPV', 'CV', '카보베르데');
INSERT INTO country_code(code3, code2, country) VALUES('KAZ', 'KZ', '카자흐스탄');
INSERT INTO country_code(code3, code2, country) VALUES('QAT', 'QA', '카타르');
INSERT INTO country_code(code3, code2, country) VALUES('KHM', 'KH', '캄보디아');
INSERT INTO country_code(code3, code2, country) VALUES('CAN', 'CA', '캐나다');
INSERT INTO country_code(code3, code2, country) VALUES('KEN', 'KE', '케냐');
INSERT INTO country_code(code3, code2, country) VALUES('CYM', 'KY', '케이맨 제도');
INSERT INTO country_code(code3, code2, country) VALUES('COM', 'KM', '코모로');
INSERT INTO country_code(code3, code2, country) VALUES('CRI', 'CR', '코스타리카');
INSERT INTO country_code(code3, code2, country) VALUES('CCK', 'CC', '코코스 제도');
INSERT INTO country_code(code3, code2, country) VALUES('CIV', 'CI', '코트디부아르');
INSERT INTO country_code(code3, code2, country) VALUES('COL', 'CO', '콜롬비아');
INSERT INTO country_code(code3, code2, country) VALUES('COG', 'CG', '콩고 공화국');
INSERT INTO country_code(code3, code2, country) VALUES('COD', 'CD', '콩고 민주 공화국');
INSERT INTO country_code(code3, code2, country) VALUES('CUB', 'CU', '쿠바');
INSERT INTO country_code(code3, code2, country) VALUES('KWT', 'KW', '쿠웨이트');
INSERT INTO country_code(code3, code2, country) VALUES('COK', 'CK', '쿡 제도');
INSERT INTO country_code(code3, code2, country) VALUES('CUW', 'CW', '퀴라소');
INSERT INTO country_code(code3, code2, country) VALUES('HRV', 'HR', '크로아티아');
INSERT INTO country_code(code3, code2, country) VALUES('CXR', 'CX', '크리스마스 섬');
INSERT INTO country_code(code3, code2, country) VALUES('KGZ', 'KG', '키르기스스탄');
INSERT INTO country_code(code3, code2, country) VALUES('KIR', 'KI', '키리바시');
INSERT INTO country_code(code3, code2, country) VALUES('CYP', 'CY', '키프로스');
INSERT INTO country_code(code3, code2, country) VALUES('TJK', 'TJ', '타지키스탄');
INSERT INTO country_code(code3, code2, country) VALUES('TZA', 'TZ', '탄자니아');
INSERT INTO country_code(code3, code2, country) VALUES('THA', 'TH', '태국');
INSERT INTO country_code(code3, code2, country) VALUES('TCA', 'TC', '터크스 케이커스 제도');
INSERT INTO country_code(code3, code2, country) VALUES('TUR', 'TR', '터키');
INSERT INTO country_code(code3, code2, country) VALUES('TGO', 'TG', '토고');
INSERT INTO country_code(code3, code2, country) VALUES('TKL', 'TK', '토켈라우');
INSERT INTO country_code(code3, code2, country) VALUES('TON', 'TO', '통가');
INSERT INTO country_code(code3, code2, country) VALUES('TKM', 'TM', '투르크메니스탄');
INSERT INTO country_code(code3, code2, country) VALUES('TUV', 'TV', '투발루');
INSERT INTO country_code(code3, code2, country) VALUES('TUN', 'TN', '튀니지');
INSERT INTO country_code(code3, code2, country) VALUES('TTO', 'TT', '트리니다드 토바고');
INSERT INTO country_code(code3, code2, country) VALUES('PAN', 'PA', '파나마');
INSERT INTO country_code(code3, code2, country) VALUES('PRY', 'PY', '파라과이');
INSERT INTO country_code(code3, code2, country) VALUES('PAK', 'PK', '파키스탄');
INSERT INTO country_code(code3, code2, country) VALUES('PNG', 'PG', '파푸아뉴기니');
INSERT INTO country_code(code3, code2, country) VALUES('PLW', 'PW', '팔라우');
INSERT INTO country_code(code3, code2, country) VALUES('PSE', 'PS', '팔레스타인');
INSERT INTO country_code(code3, code2, country) VALUES('FRO', 'FO', '페로 제도');
INSERT INTO country_code(code3, code2, country) VALUES('PER', 'PE', '페루');
INSERT INTO country_code(code3, code2, country) VALUES('PRT', 'PT', '포르투갈');
INSERT INTO country_code(code3, code2, country) VALUES('FLK', 'FK', '포클랜드 제도');
INSERT INTO country_code(code3, code2, country) VALUES('POL', 'PL', '폴란드');
INSERT INTO country_code(code3, code2, country) VALUES('PRI', 'PR', '푸에르토리코');
INSERT INTO country_code(code3, code2, country) VALUES('FRA', 'FR', '프랑스');
INSERT INTO country_code(code3, code2, country) VALUES('GUF', 'GF', '프랑스령 기아나');
INSERT INTO country_code(code3, code2, country) VALUES('ATF', 'TF', '프랑스령 남방 및 남극');
INSERT INTO country_code(code3, code2, country) VALUES('PYF', 'PF', '프랑스령 폴리네시아');
INSERT INTO country_code(code3, code2, country) VALUES('FJI', 'FJ', '피지');
INSERT INTO country_code(code3, code2, country) VALUES('FIN', 'FI', '핀란드');
INSERT INTO country_code(code3, code2, country) VALUES('PHL', 'PH', '필리핀');
INSERT INTO country_code(code3, code2, country) VALUES('PCN', 'PN', '핏케언 제도');
INSERT INTO country_code(code3, code2, country) VALUES('HMD', 'HM', '허드 맥도널드 제도');
INSERT INTO country_code(code3, code2, country) VALUES('HUN', 'HU', '헝가리');
INSERT INTO country_code(code3, code2, country) VALUES('HKG', 'HK', '홍콩');

INSERT INTO member_type(CODE, TYPE) VALUES(1, 'personal');
INSERT INTO member_type(CODE, TYPE) VALUES(2, 'institutional');
INSERT INTO member_type(CODE, TYPE) VALUES(3, 'admin');

INSERT INTO member(id, PASSWORD, first_name_en, last_name_en, first_name_ko, last_name_ko, country_code, institute, type_code)
VALUES ('admin', 'admin', 'test', 'test', 'test', 'test', 'KOR', '고려대학교', 3);